services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "npm run build && npx prisma migrate deploy && npm start"
    depends_on:
      - db

  db:
    image: postgres
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  test:
    build: .
    container_name: test_container
    environment:
      - NODE_ENV=test
    command: npm test
    volumes:
      - .:/app
