services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  test:
    build: .
    container_name: test_container
    environment:
      - NODE_ENV=test
    command: npm test
    volumes:
      - .:/app
