services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres
    shm_size: 128mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"

  test:
    build: .
    container_name: test_container
    environment:
      - NODE_ENV=test
    command: npm test
    volumes:
      - .:/app
